version: v1

defaults:
  - docker-image

bundle:
  builds:
    - filter: on-every-commit
      config:
        platform: nodejs
        platform_version: "14"
        exclude_paths:
          - test
          - backfill
          - cloudformation
